[package]
name = "youGotMail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.5.0"
mail-send = "0.4.9"
tokio = { version = "1.41.1", features = ["full"] }
